version: '3'

services:
  nextjs:
    image: test-conn-client
    build: ./client/
    container_name: nextjs
    networks:
      - app-network

  express:
    image: test-conn-server
    build: ./server/
    container_name: express
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - app-network

networks:
  app-network:
    driver: bridge